import { Box } from "@mui/material";
import Head from "next/head";
import CurrentDeals from "../Components/CurrentDeals";
import Footer from "../Components/Footer";
import Header from "../Components/Header";
import NewlyAddedDeals from "../Components/NewlyAddedDeals";
import ServicesForYou from "../Components/ServicesForYou";
import Slider from "../Components/Slider";
import dummyData from "../dummyData.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Buy Button.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header />
        <Slider />
        <CurrentDeals data={dummyData} />
        <NewlyAddedDeals data={dummyData} />
        <ServicesForYou />
        <Footer />
      </Box>
    </div>
  );
}
